; ============================================================
; Konfigurasi PlatformIO untuk Sistem Monitoring AWD
; Board: ESP32 DevKit-C V4 (WROOM-32D)
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan upload & monitor serial
monitor_speed = 115200
upload_speed = 921600

; Library yang dibutuhkan (otomatis diunduh PlatformIO)
lib_deps =
    bblanchon/ArduinoJson@^7.0.4

; Flag build
build_flags =
    -D CORE_DEBUG_LEVEL=3
